name: Convert and Upload

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: ls -alh
      - run: wget https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.6.2/linux-pandoc_2_9_2.tar.gz
      - run: tar xvf linux-pandoc_2_9_2.tar.gz 
      - name: convert
        uses: docker://pandoc/latex:2.9
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            --from=markdown
            --to=latex
            --template=template.latex
            --filter=pandoc-crossref
            --filter=pandoc-citeproc
            --bibliography=bibliography.bib
            --csl=bibliography.csl
            --output=article.pdf
            content.md      
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: pub
          path: article.pdf 
        
